# compose file to test building project with docker
# usage: HOST_PORT=8081 docker-compose -f docker-compose.dev.yml up -d --build
version: '3.8'
services:
  frontend:
    build:
      context: .
    ports:
      - '${HOST_PORT}:80'

